%% load datadir
datadir = '../../data_processed/bayesdata';
[~,datalists] = W.dir(fullfile(datadir, '*.mat'));
%% setup full path
fullpt = 'W:/Projects_Wang/Projects_submitted/Fellous_Siyu_RatEE_InRevision/Codes_RatEE/code_5_bayesian/models';
outputdir = 'W:/Projects_Wang/Projects_submitted/Fellous_Siyu_RatEE_InRevision/result_bayes';
%%
mi = 0;

mi = mi + 1;
modelname{mi} = 'model_rat_history.txt';
params{mi} = {'noise_k','noise_lambda', 'noise', ...
    'thres_a', 'thres_b', 'thres', ...
    'bias_mu','bias_sigma', 'bias', ...
    'lr_last','lr_last_a','lr_last_b', ...
    'lr_lastgs','lr_lastgs_a','lr_lastgs_b', ...
    'tlrlast', 'tlrlastgs', ...
    'dbias','dthres', 'dnoise',...
    'tnoise','tthres','tbias'};
init0{mi} = struct;


mi = mi + 1;
modelname{mi} = 'model_simple_history.txt';
% params{mi} = {'noise_k','noise_lambda', 'noise', ...
%     'thres_mu', 'thres_sigma', ...
%     'tnoise','tthres'};
params{mi} = {'noise_k','noise_lambda', 'noise', ...
    'thres_a', 'thres_b', 'thres', ...
    'bias_mu','bias_sigma', 'bias', ...
    'lr_last','lr_last_a','lr_last_b', ...
    'lr_lastgs','lr_lastgs_a','lr_lastgs_b', ...
    'tlrlast', 'tlrlastgs', ...
    'tnoise','tthres','tbias'};
init0{mi} = struct;

mi = mi + 1;
modelname{mi} = 'model_human_full_history.txt';
params{mi} = {'noise_k','noise_lambda', 'noise', ...
    'thres_a', 'thres_b', 'thres', ...
    'bias_mu','bias_sigma', 'bias', ...
    'lr_last','lr_last_a','lr_last_b', ...
    'lr_lastgs','lr_lastgs_a','lr_lastgs_b', ...
    'tlrlast', 'tlrlastgs', ...
    'tnoise','tthres','tbias'};
%     'thres_mu', 'thres_sigma', ...
init0{mi} = struct;




mi = mi + 1;
modelname{mi} = 'model_simple_1H_history.txt';
% params{mi} = {'noise_k','noise_lambda', 'noise', ...
%     'thres_mu', 'thres_sigma', ...
%     'tnoise','tthres'};
params{mi} = {'noise_k','noise_lambda', 'noise', ...
    'thres_a', 'thres_b', 'thres', ...
    'bias_mu','bias_sigma', 'bias', ...
    'lr_last','lr_last_a','lr_last_b', ...
    'lr_lastgs','lr_lastgs_a','lr_lastgs_b', ...
    'tlrlast', 'tlrlastgs', ...
    'tnoise','tthres','tbias'};
init0{mi} = struct;
%%
datalists.modeli(:,1) = 2;
datalists = datalists(datalists.folder_name ~= "bayes_long01.mat",:);
datalists(datalists.folder_name == "bayes_within_all.mat",:).modeli = 1;
datalists(datalists.folder_name == "bayes_human_full.mat",:).modeli = 3;
datalists(datalists.folder_name == "bayes_control.mat",:).modeli = 4;

%% setup JAGS/params
wj = W_JAGS();
wj.isoverwrite = true;
% wj.setup_params;
wj.setup_params(4, 10000, 10000);
%% run models
for di = [1:size(datalists,1)]
    %% load data
    bayesdata = importdata(fullfile(datalists.folder_path(di), datalists.folder_name(di)));
    wj.setup_data_dir(bayesdata.bayesdata, outputdir);
    %% run
    mmi = datalists.modeli(di);
%     for mmi = wselect
%         try
            disp(sprintf('running dataset %d, model %d: %s', di, mmi,modelname{mmi}));
            outfile = W.file_deext(datalists.folder_name(di));
            outfile = replace(outfile, 'bayes_', replace(modelname{mmi},'.txt','_'));
            wj.setup(fullfile(fullpt, modelname{mmi}), params{mmi}, init0{mmi}, outfile);
            wj.run;
%         catch
%             warning('!!!!!!!!!!!!!!!!!!failed');
%         end
%     end
end