% % version list
function versionlist = getversionlist(datadir, projectname)
%     ratname = 'Tianqi';
%     ratdir = fullfile(datadir, [projectname '_' ratname], 'RawData');
%     v = string; d = [];
%     i = 0;
%     i = i+1;
%     v(i) = string('Guided1_Sound');
%     d{i} = getratdateranges(ratdir, {'070620','071020'});
%     versionlist.(ratname).folder = ratdir;
%     versionlist.(ratname).version = v;
%     versionlist.(ratname).dates = d;


    ratname = 'Ratzo';
    ratdir = fullfile(datadir, [projectname '_' ratname], 'RawData');
    v = string; d = [];
    i = 0;
    i = i+1;
%     v(i) = string('Pretraining');
%     d{i} = getratdateranges(ratdir, {'012120','030320'});
%     i = i+1;
%     v(i) = string('Guided_twice');
%     d{i} = getratdateranges(ratdir, {'030420','032120'});
%     i = i+1;
%     v(i) = string('Guided_Long');
%     d{i} = getratdateranges(ratdir, {'032420','032820'});
%     i = i+1;
%     v(i) = string('Guided_Short');
%     d{i} = getratdateranges(ratdir, {'033020','041220'});
%     i = i+1;
%     v(i) = string('Guided_Long');
%     d{i} = getratdateranges(ratdir, {'041320','050920'});
%     i = i+1;
%     v(i) = string('Guided');
%     d{i} = getratdateranges(ratdir, {'051020','051620'});
%     i = i+1;
%     v(i) = string('VariableGuided');
%     d{i} = getratdateranges(ratdir, {'052020','052720'});
%     i = i+1;
%     v(i) = string('FreeChoice_Sound');
%     d{i} = getratdateranges(ratdir, {'060220','062420'});
%     i = i+1;
%     v(i) = string('Guided2_Sound');
%     d{i} = getratdateranges(ratdir, {'062820','070320'});
    i = i+1;
    v(i) = string('Guided1_Sound');
    d{i} = getratdateranges(ratdir, {'070620','071020'});
    versionlist.(ratname).folder = ratdir;
    versionlist.(ratname).version = v;
    versionlist.(ratname).dates = d;
    
    
    ratname = 'Rizzo';
    ratdir = fullfile(datadir, [projectname '_' ratname], 'RawData');
    v = string; d = [];
    i = 0;
    i = i+1;
%     v(i) = string('Pretraining');
%     d{i} = getratdateranges(ratdir, {'012420','030320'});
%     i = i+1;
%     v(i) = string('Guided_twice');
%     d{i} = getratdateranges(ratdir, {'030420','032120'});
%     i = i+1;
%     v(i) = string('Guided_Long');
%     d{i} = getratdateranges(ratdir, {'032420','032820'});
%     i = i+1;
%     v(i) = string('Guided_Short');
%     d{i} = getratdateranges(ratdir, {'033020','041220'});
%     i = i+1;
%     v(i) = string('Guided_Long');
%     d{i} = getratdateranges(ratdir, {'041320','050920'});
%     i = i+1;
%     v(i) = string('Guided');
%     d{i} = getratdateranges(ratdir, {'051020','051620'});
%     i = i+1;
%     v(i) = string('VariableGuided');
%     d{i} = getratdateranges(ratdir, {'052020','052720'});
%     i = i+1;
%     v(i) = string('FreeChoice_Sound');
%     d{i} = getratdateranges(ratdir, {'060220','062420'});
%     i = i+1;
%     v(i) = string('Guided2_Sound');
%     d{i} = getratdateranges(ratdir, {'062820','070320'});
    i = i+1;
    v(i) = string('Guided1_Sound');
    d{i} = getratdateranges(ratdir, {'070620','071020'});
    versionlist.(ratname).folder = ratdir;
    versionlist.(ratname).version = v;
    versionlist.(ratname).dates = d;
end
